import { PrismaClient } from "@prisma/client"
import bcrypt from "bcryptjs"

const prisma = new PrismaClient()

const COMPETITOR_DATA = [
  {
    name: "Minimalist",
    website: "https://beminimalist.co",
    metaAdUrl: "https://www.facebook.com/ads/library/?q=beminimalist",
    logo: "https://picsum.photos/seed/minimalist/80/80",
    industry: "skincare",
    ads: [
      {
        headline: "10% Niacinamide + Zinc. Real results. ₹599.",
        body: "Science-backed formulas. No fillers, no fluff. Just what your skin actually needs. 2M+ happy customers don't lie.",
        cta: "Shop Now",
        imageUrl: "https://picsum.photos/seed/min1/600/600",
        landingUrl: "https://beminimalist.co/products/niacinamide",
        hookType: "authority",
        angleType: "science_backed",
        formatType: "demo",
        offerType: "none",
        firstSeen: new Date("2024-01-15"),
        lastSeen: new Date("2024-02-20"),
      },
      {
        headline: "Your skin barrier is crying. Here's why.",
        body: "Harsh cleansers. Pollution. Stress. Your barrier takes a hit daily. Ceramides can fix that. Starting ₹449.",
        cta: "Fix My Barrier",
        imageUrl: "https://picsum.photos/seed/min2/600/600",
        landingUrl: "https://beminimalist.co/products/ceramide",
        hookType: "problem",
        angleType: "science_backed",
        formatType: "ugc",
        offerType: "none",
        firstSeen: new Date("2024-01-20"),
        lastSeen: new Date("2024-02-18"),
      },
      {
        headline: "4 weeks on Retinol 0.3%. Her results.",
        body: "Fine lines. Then not. Retinol 0.3% in squalane. Gentle enough for beginners. Effective enough for everyone. ₹699.",
        cta: "See Results",
        imageUrl: "https://picsum.photos/seed/min3/600/600",
        landingUrl: "https://beminimalist.co/products/retinol",
        hookType: "transformation",
        angleType: "science_backed",
        formatType: "testimonial",
        offerType: "none",
        firstSeen: new Date("2024-02-01"),
        lastSeen: new Date("2024-02-22"),
      },
      {
        headline: "3 serums. 1 routine. Under ₹1,499.",
        body: "The starter pack your skin has been waiting for. Niacinamide + Vitamin C + SPF. Bundle and save 20%.",
        cta: "Get the Bundle",
        imageUrl: "https://picsum.photos/seed/min4/600/600",
        landingUrl: "https://beminimalist.co/collections/bundles",
        hookType: "curiosity",
        angleType: "affordability",
        formatType: "demo",
        offerType: "bundle",
        firstSeen: new Date("2024-02-10"),
        lastSeen: new Date("2024-02-23"),
      },
      {
        headline: "Dermatologist-tested. Not influencer-approved.",
        body: "We don't do celebrity endorsements. We do clinical evidence. 8 dermatologists. 3,000 volunteers. That's how we formulate.",
        cta: "Read the Science",
        imageUrl: "https://picsum.photos/seed/min5/600/600",
        landingUrl: "https://beminimalist.co/pages/science",
        hookType: "authority",
        angleType: "science_backed",
        formatType: "founder_led",
        offerType: "none",
        firstSeen: new Date("2024-02-14"),
        lastSeen: new Date("2024-02-24"),
      },
    ],
  },
  {
    name: "Dot & Key",
    website: "https://www.dotandkey.com",
    metaAdUrl: "https://www.facebook.com/ads/library/?q=dotandkey",
    logo: "https://picsum.photos/seed/dotandkey/80/80",
    industry: "skincare",
    ads: [
      {
        headline: "Watermelon Glow. Not just a vibe—it's science.",
        body: "Watermelon seed oil + Hyaluronic Acid. Plump, juicy skin in 7 days. Dermatologist tested. ₹649.",
        cta: "Glow Now",
        imageUrl: "https://picsum.photos/seed/dk1/600/600",
        landingUrl: "https://www.dotandkey.com/products/watermelon-glow",
        hookType: "curiosity",
        angleType: "emotional",
        formatType: "ugc",
        offerType: "none",
        firstSeen: new Date("2024-01-18"),
        lastSeen: new Date("2024-02-22"),
      },
      {
        headline: "SPF 50 that doesn't feel like sunscreen. Finally.",
        body: "Lightweight. Invisible. Zero white cast. 500K+ people switched. Your skin won't miss the old one.",
        cta: "Try It",
        imageUrl: "https://picsum.photos/seed/dk2/600/600",
        landingUrl: "https://www.dotandkey.com/products/spf",
        hookType: "problem",
        angleType: "convenience",
        formatType: "ugc",
        offerType: "free_shipping",
        firstSeen: new Date("2024-01-25"),
        lastSeen: new Date("2024-02-23"),
      },
      {
        headline: "15 dermatologists consulted. 1 serum made.",
        body: "After 15 dermat consultations and 18 months of formulation, we rebuilt Vitamin C. Stable. Visible. Real.",
        cta: "Shop Vitamin C",
        imageUrl: "https://picsum.photos/seed/dk3/600/600",
        landingUrl: "https://www.dotandkey.com/products/vitamin-c",
        hookType: "authority",
        angleType: "science_backed",
        formatType: "founder_led",
        offerType: "none",
        firstSeen: new Date("2024-02-05"),
        lastSeen: new Date("2024-02-21"),
      },
      {
        headline: "Your 3-step dewy skin routine. ₹1,299.",
        body: "Cleanser + Toner + Moisturiser. Matched to your skin type. Curated for Indian climate. Start your glow.",
        cta: "Build My Routine",
        imageUrl: "https://picsum.photos/seed/dk4/600/600",
        landingUrl: "https://www.dotandkey.com/collections/starter",
        hookType: "curiosity",
        angleType: "convenience",
        formatType: "demo",
        offerType: "starter_pack",
        firstSeen: new Date("2024-02-12"),
        lastSeen: new Date("2024-02-24"),
      },
    ],
  },
  {
    name: "Mamaearth",
    website: "https://mamaearth.in",
    metaAdUrl: "https://www.facebook.com/ads/library/?q=mamaearth",
    logo: "https://picsum.photos/seed/mamaearth/80/80",
    industry: "skincare",
    ads: [
      {
        headline: "Toxin-free doesn't mean less effective.",
        body: "No sulfates. No parabens. No mineral oil. All the hydration your skin craves. India's most trusted natural brand.",
        cta: "Shop Toxin-Free",
        imageUrl: "https://picsum.photos/seed/me1/600/600",
        landingUrl: "https://mamaearth.in/collections/face-wash",
        hookType: "problem",
        angleType: "emotional",
        formatType: "ugc",
        offerType: "none",
        firstSeen: new Date("2024-01-10"),
        lastSeen: new Date("2024-02-22"),
      },
      {
        headline: "Good for you. Good for the planet.",
        body: "1% of every order plants a tree. 500,000+ trees planted. Your purchase = a greener India.",
        cta: "Shop & Plant",
        imageUrl: "https://picsum.photos/seed/me2/600/600",
        landingUrl: "https://mamaearth.in",
        hookType: "social_proof",
        angleType: "emotional",
        formatType: "meme",
        offerType: "none",
        firstSeen: new Date("2024-01-28"),
        lastSeen: new Date("2024-02-20"),
      },
      {
        headline: "10,000+ reviews. Same onion hair oil.",
        body: "Reduces hair fall in 30 days. India's most-reviewed hair care product. Backed by science. Made in India.",
        cta: "Fight Hair Fall",
        imageUrl: "https://picsum.photos/seed/me3/600/600",
        landingUrl: "https://mamaearth.in/collections/hair-care",
        hookType: "social_proof",
        angleType: "science_backed",
        formatType: "testimonial",
        offerType: "none",
        firstSeen: new Date("2024-02-08"),
        lastSeen: new Date("2024-02-23"),
      },
    ],
  },
  {
    name: "OZiva",
    website: "https://oziva.in",
    metaAdUrl: "https://www.facebook.com/ads/library/?q=oziva",
    logo: "https://picsum.photos/seed/oziva/80/80",
    industry: "wellness",
    ads: [
      {
        headline: "Clean protein. Real results. No compromise.",
        body: "Plant-based. No artificial sweeteners. No added sugar. 27g protein per serving. Your body deserves better.",
        cta: "Try OZiva",
        imageUrl: "https://picsum.photos/seed/oz1/600/600",
        landingUrl: "https://oziva.in/collections/protein",
        hookType: "authority",
        angleType: "science_backed",
        formatType: "founder_led",
        offerType: "starter_pack",
        firstSeen: new Date("2024-01-12"),
        lastSeen: new Date("2024-02-23"),
      },
      {
        headline: "Why are fitness influencers switching to plant protein?",
        body: "Better digestion. No bloating. Same gains. See what 500K+ customers already know about clean nutrition.",
        cta: "See Why",
        imageUrl: "https://picsum.photos/seed/oz2/600/600",
        landingUrl: "https://oziva.in/collections/protein",
        hookType: "curiosity",
        angleType: "science_backed",
        formatType: "testimonial",
        offerType: "none",
        firstSeen: new Date("2024-01-22"),
        lastSeen: new Date("2024-02-21"),
      },
      {
        headline: "90 days. Clean nutrition. Her transformation.",
        body: "Priya lost 8kg without crash diets. No starving. Just OZiva Protein + a little discipline. Could be your story.",
        cta: "Start My Journey",
        imageUrl: "https://picsum.photos/seed/oz3/600/600",
        landingUrl: "https://oziva.in/collections/weight-management",
        hookType: "transformation",
        angleType: "emotional",
        formatType: "testimonial",
        offerType: "subscription",
        firstSeen: new Date("2024-02-02"),
        lastSeen: new Date("2024-02-24"),
      },
      {
        headline: "First order? ₹300 off, no code needed.",
        body: "Try India's cleanest protein risk-free. ₹300 off your first order + free shaker. Auto-applied at checkout.",
        cta: "Claim ₹300 Off",
        imageUrl: "https://picsum.photos/seed/oz4/600/600",
        landingUrl: "https://oziva.in",
        hookType: "curiosity",
        angleType: "affordability",
        formatType: "demo",
        offerType: "discount",
        firstSeen: new Date("2024-02-15"),
        lastSeen: new Date("2024-02-25"),
      },
    ],
  },
  {
    name: "MuscleBlaze",
    website: "https://www.muscleblaze.com",
    metaAdUrl: "https://www.facebook.com/ads/library/?q=muscleblaze",
    logo: "https://picsum.photos/seed/muscleblaze/80/80",
    industry: "fitness",
    ads: [
      {
        headline: "India's #1 protein brand. 8 years running.",
        body: "100g protein per 100g serving. Informed Sport certified. Banned-substance tested. Zero compromises.",
        cta: "Shop Whey",
        imageUrl: "https://picsum.photos/seed/mb1/600/600",
        landingUrl: "https://www.muscleblaze.com/whey-protein",
        hookType: "authority",
        angleType: "premium",
        formatType: "demo",
        offerType: "none",
        firstSeen: new Date("2024-01-08"),
        lastSeen: new Date("2024-02-22"),
      },
      {
        headline: "Gym bag essentials. One bundle. Save ₹1,200.",
        body: "Whey + Pre-workout + Creatine. Everything you need stacked at ₹3,499. Your gains just got cheaper.",
        cta: "Get the Stack",
        imageUrl: "https://picsum.photos/seed/mb2/600/600",
        landingUrl: "https://www.muscleblaze.com/bundles",
        hookType: "problem",
        angleType: "affordability",
        formatType: "demo",
        offerType: "bundle",
        firstSeen: new Date("2024-01-30"),
        lastSeen: new Date("2024-02-24"),
      },
      {
        headline: "He trained for 6 months with only MuscleBlaze.",
        body: "Sahil Khan. 6 months. Biozyme Performance Whey. One brand. Documented everything. Watch the full journey.",
        cta: "Watch Now",
        imageUrl: "https://picsum.photos/seed/mb3/600/600",
        landingUrl: "https://www.muscleblaze.com",
        hookType: "social_proof",
        angleType: "premium",
        formatType: "founder_led",
        offerType: "none",
        firstSeen: new Date("2024-02-12"),
        lastSeen: new Date("2024-02-23"),
      },
    ],
  },
  {
    name: "Snitch",
    website: "https://www.snitch.co.in",
    metaAdUrl: "https://www.facebook.com/ads/library/?q=snitch",
    logo: "https://picsum.photos/seed/snitch/80/80",
    industry: "fashion",
    ads: [
      {
        headline: "You finally found menswear that gets it.",
        body: "Oversized. Anti-fit. Drop-crotch. Style that doesn't ask for permission. New drop every Monday.",
        cta: "Shop the Drop",
        imageUrl: "https://picsum.photos/seed/sn1/600/600",
        landingUrl: "https://www.snitch.co.in/collections/new-arrivals",
        hookType: "emotional",
        angleType: "premium",
        formatType: "ugc",
        offerType: "none",
        firstSeen: new Date("2024-01-14"),
        lastSeen: new Date("2024-02-21"),
      },
      {
        headline: "500 pieces. 48 hours. No restocks.",
        body: "We don't do restocks. Co-ord sets from ₹1,499. This is your window. Move fast.",
        cta: "Shop Now",
        imageUrl: "https://picsum.photos/seed/sn2/600/600",
        landingUrl: "https://www.snitch.co.in",
        hookType: "curiosity",
        angleType: "premium",
        formatType: "demo",
        offerType: "none",
        firstSeen: new Date("2024-02-06"),
        lastSeen: new Date("2024-02-24"),
      },
      {
        headline: "Free shipping above ₹999. Always.",
        body: "No code. No minimum fuss. Great menswear, fast delivery. Browse the bestsellers.",
        cta: "Shop Bestsellers",
        imageUrl: "https://picsum.photos/seed/sn3/600/600",
        landingUrl: "https://www.snitch.co.in/collections/bestsellers",
        hookType: "problem",
        angleType: "convenience",
        formatType: "demo",
        offerType: "free_shipping",
        firstSeen: new Date("2024-02-18"),
        lastSeen: new Date("2024-02-25"),
      },
    ],
  },
  {
    name: "Bewakoof",
    website: "https://www.bewakoof.com",
    metaAdUrl: "https://www.facebook.com/ads/library/?q=bewakoof",
    logo: "https://picsum.photos/seed/bewakoof/80/80",
    industry: "fashion",
    ads: [
      {
        headline: "Express your weird. Wear it loudly.",
        body: "Pop culture tees. Anime prints. Meme merch. Casual that speaks for you when words fail.",
        cta: "Be Weird",
        imageUrl: "https://picsum.photos/seed/bw1/600/600",
        landingUrl: "https://www.bewakoof.com/t-shirts",
        hookType: "emotional",
        angleType: "emotional",
        formatType: "meme",
        offerType: "none",
        firstSeen: new Date("2024-01-16"),
        lastSeen: new Date("2024-02-22"),
      },
      {
        headline: "₹399 tees. Premium quality. Not a typo.",
        body: "We cut out the middleman so you don't cut corners. 100% cotton. 100% personality. No apologies.",
        cta: "Shop Under ₹499",
        imageUrl: "https://picsum.photos/seed/bw2/600/600",
        landingUrl: "https://www.bewakoof.com",
        hookType: "curiosity",
        angleType: "affordability",
        formatType: "demo",
        offerType: "discount",
        firstSeen: new Date("2024-01-24"),
        lastSeen: new Date("2024-02-23"),
      },
    ],
  },
  {
    name: "The Souled Store",
    website: "https://www.thesouledstore.com",
    metaAdUrl: "https://www.facebook.com/ads/library/?q=thesouledstore",
    logo: "https://picsum.photos/seed/souled/80/80",
    industry: "fashion",
    ads: [
      {
        headline: "Your fandom deserves better merch.",
        body: "Officially licensed Marvel, DC, Harry Potter. Not knockoffs. Real quality. Finally in India.",
        cta: "Shop by Fandom",
        imageUrl: "https://picsum.photos/seed/ts1/600/600",
        landingUrl: "https://www.thesouledstore.com/collections/official",
        hookType: "emotional",
        angleType: "premium",
        formatType: "demo",
        offerType: "none",
        firstSeen: new Date("2024-01-19"),
        lastSeen: new Date("2024-02-21"),
      },
      {
        headline: "Buy 3, get 1 free. Always. No fine print.",
        body: "Mix and match across all fandoms. No minimum. No expiry. Just more merch for less money.",
        cta: "Start Building",
        imageUrl: "https://picsum.photos/seed/ts2/600/600",
        landingUrl: "https://www.thesouledstore.com",
        hookType: "social_proof",
        angleType: "affordability",
        formatType: "demo",
        offerType: "bundle",
        firstSeen: new Date("2024-02-03"),
        lastSeen: new Date("2024-02-24"),
      },
    ],
  },
]

const INSIGHTS_DATA = [
  {
    title: "Barrier repair messaging is rising across skincare",
    summary:
      "3 of 4 skincare competitors have introduced 'barrier repair' language in the last 30 days. Minimalist and Dot & Key are leading this narrative, signaling a market shift toward skin health over pure beauty aesthetics. Consumers are increasingly responding to science-led, functional positioning.",
    confidence: 0.87,
    competitors: JSON.stringify(["Minimalist", "Dot & Key", "Mamaearth"]),
    tags: JSON.stringify(["skincare", "barrier-repair", "science-backed", "trend"]),
    category: "trend",
    isNew: true,
    createdAt: new Date("2024-02-20"),
  },
  {
    title: "UGC selfie-style video ads dominate recent skincare creatives",
    summary:
      "UGC and selfie-format video creatives have increased 40% across skincare competitors in the past 6 weeks. Dot & Key and OZiva are running these most aggressively. Run-duration signals suggest these formats consistently outperform polished product shots.",
    confidence: 0.92,
    competitors: JSON.stringify(["Dot & Key", "OZiva", "Mamaearth"]),
    tags: JSON.stringify(["ugc", "video", "creative-format", "skincare"]),
    category: "pattern",
    isNew: true,
    createdAt: new Date("2024-02-19"),
  },
  {
    title: "Bundle offers increasing across wellness brands",
    summary:
      "OZiva and MuscleBlaze both launched bundle-first campaigns this month. The 'stack everything you need' positioning is outpacing single-product ads. This may indicate DTC brands are shifting toward higher AOV strategies ahead of Q1 revenue push.",
    confidence: 0.79,
    competitors: JSON.stringify(["OZiva", "MuscleBlaze"]),
    tags: JSON.stringify(["bundles", "aov", "wellness", "offers"]),
    category: "pattern",
    isNew: true,
    createdAt: new Date("2024-02-18"),
  },
  {
    title: "Authority hooks surging in wellness and skincare",
    summary:
      "Phrases like 'Dermat tested', 'Informed Sport certified', and 'Science-backed' appear in 6 of 8 recent wellness ads. The market is moving toward credibility signaling as a primary hook—likely a response to increasing consumer skepticism about supplement and skincare claims.",
    confidence: 0.83,
    competitors: JSON.stringify(["OZiva", "MuscleBlaze", "Dot & Key", "Minimalist"]),
    tags: JSON.stringify(["authority", "trust", "certification", "hooks"]),
    category: "trend",
    isNew: false,
    createdAt: new Date("2024-02-16"),
  },
  {
    title: "Fashion brands pairing urgency with scarcity messaging",
    summary:
      "Snitch and The Souled Store combine limited-quantity ('500 pieces') with time pressure ('48 hours'). This pairing creates stronger FOMO than either tactic alone, and both brands are running these creatives longer than their standard campaigns—a run-duration signal of high performance.",
    confidence: 0.76,
    competitors: JSON.stringify(["Snitch", "The Souled Store"]),
    tags: JSON.stringify(["urgency", "scarcity", "fomo", "fashion"]),
    category: "pattern",
    isNew: false,
    createdAt: new Date("2024-02-14"),
  },
  {
    title: "Transformation narratives outperforming product demos",
    summary:
      "Ads featuring before/after stories and customer journeys are running 2x longer than product demo ads. Mamaearth, OZiva, and Minimalist are all investing heavily in testimonial and transformation formats, suggesting higher downstream conversion rates.",
    confidence: 0.88,
    competitors: JSON.stringify(["Mamaearth", "OZiva", "Minimalist"]),
    tags: JSON.stringify(["transformation", "testimonial", "social-proof", "creative"]),
    category: "opportunity",
    isNew: false,
    createdAt: new Date("2024-02-12"),
  },
  {
    title: "Affordability messaging resurges post-January",
    summary:
      "February has seen a notable uptick in price-anchored messaging across fashion and wellness categories. '₹399', 'under ₹1499', and 'save ₹1200' are appearing in headlines more frequently—possibly a response to post-festive budget consciousness.",
    confidence: 0.71,
    competitors: JSON.stringify(["Bewakoof", "OZiva", "MuscleBlaze", "Snitch"]),
    tags: JSON.stringify(["price", "affordability", "february-trend"]),
    category: "trend",
    isNew: false,
    createdAt: new Date("2024-02-10"),
  },
  {
    title: "Free shipping is becoming a baseline expectation in fashion",
    summary:
      "Every fashion brand tracked now features free shipping in at least one active creative. Competing on free shipping alone is no longer differentiating—it's become table stakes. Brands will need to find new friction-removers to stand out.",
    confidence: 0.94,
    competitors: JSON.stringify(["Snitch", "Bewakoof", "The Souled Store"]),
    tags: JSON.stringify(["shipping", "offers", "fashion", "baseline"]),
    category: "pattern",
    isNew: false,
    createdAt: new Date("2024-02-08"),
  },
  {
    title: "Subscription positioning emerging in wellness for the first time",
    summary:
      "OZiva has introduced subscription language into 2 active ads, emphasizing monthly savings and convenience. This is the first clear subscription push in the tracked wellness segment—watch if MuscleBlaze and Wellbeing Nutrition follow this playbook.",
    confidence: 0.68,
    competitors: JSON.stringify(["OZiva"]),
    tags: JSON.stringify(["subscription", "wellness", "retention", "emerging"]),
    category: "opportunity",
    isNew: false,
    createdAt: new Date("2024-02-05"),
  },
]

async function main() {
  console.log("🌱 Seeding Signal database...")

  const hashedPassword = await bcrypt.hash("demo1234", 10)
  const user = await prisma.user.upsert({
    where: { email: "demo@signal.app" },
    update: {},
    create: {
      name: "Demo User",
      email: "demo@signal.app",
      password: hashedPassword,
    },
  })
  console.log(`✅ Created user: ${user.email}`)

  for (const { ads, ...competitorInfo } of COMPETITOR_DATA) {
    const competitor = await prisma.competitor.upsert({
      where: { name_userId: { name: competitorInfo.name, userId: user.id } },
      update: {},
      create: { ...competitorInfo, userId: user.id },
    })

    for (const ad of ads) {
      await prisma.ad.create({
        data: { ...ad, competitorId: competitor.id },
      })
    }
    console.log(`✅ ${competitor.name} — ${ads.length} ads`)
  }

  for (const insight of INSIGHTS_DATA) {
    await prisma.insight.create({ data: insight })
  }
  console.log(`✅ Created ${INSIGHTS_DATA.length} insights`)

  console.log("\n🎉 Seed complete!")
  console.log("📧 Login: demo@signal.app")
  console.log("🔑 Password: demo1234")
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
